### ISSUE TITLE
App.Update

### ISSUE THREAD

**Issue by nzgnzg73** [google-ai-edge/gallery#380]
My brother, I want to ask you when App.the update will be released. It has been two or three months and the update has not been released yet. When will it be released?

**Comment by dpknag** [comment]
Hello @nzgnzg73,

Thank you for your patience.

We just released the latest version v1.0.8. You can download it here:
[GitHub Release v1.0.8](https://github.com/google-ai-edge/gallery/releases/tag/1.0.8)
[Google Play Store](https://play.google.com/store/apps/details?id=com.google.ai.edge.gallery&pli=1)

Let us know your feedback. I am closing this issue now.

**Comment by nzgnzg73** [comment]
Bra, the problem that I told you about has not been solved or you have added small future bass, the bigger problems which were not solved yet. Meaning the one with voice, one with history and etc. Place, solve these things, eliminate voice limit You can upload as much as you want, the method of uploading and everything.
